package raymitchell.euler.problems

import raymitchell.euler.util.FibonacciSequence

/**
  * Each new term in the Fibonacci sequence is generated by adding the previous
  * two terms. By starting with 1 and 1, the first 10 terms will be:
  *
  * 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, ...
  *
  * By considering the terms in the Fibonacci sequence whose values do not
  * exceed four million, find the sum of the even-valued terms.
  */
object Problem2 {

  def solve(): Long = {
    FibonacciSequence
      .takeWhile(_ <= 4000000)
      .filter(_ % 2 == 0)
      .sum
  }
}
