package raymitchell.euler.problems

import raymitchell.euler.util.MathEx

/**
  * Each new term in the Fibonacci sequence is generated by adding the previous
  * two terms. By starting with 1 and 1, the first 10 terms will be:
  *
  * 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ...
  *
  * By considering the terms in the Fibonacci sequence whose values do not
  * exceed four million, find the sum of the even-valued terms.
  */
object Problem2 {

  def solve(): Int =
    MathEx.fibonaccis
      .takeWhile(_ <= 4000000)
      .filter(_ % 2 == 0)
      .sum
}
